name: Build APK

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Buildozer
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.android
          key: buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            openjdk-17-jdk zip unzip build-essential \
            autoconf automake libtool pkg-config \
            libffi-dev zlib1g-dev libssl-dev make
          pip install buildozer cython kivy

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
